services:

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: microservices_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-net

  service-registry:
    build: ./service-registry
    container_name: service-registry
    ports:
      - "8762:8762"
    networks:
      - microservices-net

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - service-registry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8762/eureka/
    networks:
      - microservices-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8061:8061"
    depends_on:
      - service-registry
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8762/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    networks:
      - microservices-net

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8085:8085"
    depends_on:
      - postgres
      - service-registry
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8762/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/microservices_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - microservices-net

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8086:8086"
    depends_on:
      - postgres
      - service-registry
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8762/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/microservices_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - microservices-net

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8084:8084"
    depends_on:
      - service-registry
      - config-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8762/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    networks:
      - microservices-net

volumes:
  postgres_data:

networks:
  microservices-net:
    driver: bridge